### ISSUE TITLE
type object 'NewBase' has no attribute 'django_model'

### ISSUE THREAD

**Issue by bluedazzle** [scrapy-plugins/scrapy-djangoitem#17]
I have a scrapy spider run by celery which contains django-item. And I have some errors when using scrapy-djangoitem:

```shell
Traceback (most recent call last):
  File "/usr/local/bin/celery", line 9, in <module>
    load_entry_point('celery==4.0.1', 'console_scripts', 'celery')()
  File "/usr/local/lib/python2.7/dist-packages/celery/__main__.py", line 14, in main
    _main()
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 326, in main
    cmd.execute_from_commandline(argv)
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 488, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 279, in execute_from_commandline
    argv = self.setup_app_from_commandline(argv)
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 481, in setup_app_from_commandline
    self.app = self.find_app(app)
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 503, in find_app
    return find_app(app, symbol_by_name=self.symbol_by_name)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/utils.py", line 358, in find_app
    sym = imp(app)
  File "/usr/local/lib/python2.7/dist-packages/celery/utils/imports.py", line 101, in import_from_cwd
    return imp(module, package=package)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/var/www/site/RaPo3/task_dispatch/task.py", line 9, in <module>
    from collector.collector.crawl_agent import crawl
  File "/var/www/site/RaPo3/collector/collector/crawl_agent.py", line 12, in <module>
    from spiders.coding_spider import ProxySpider
  File "/var/www/site/RaPo3/collector/collector/spiders/coding_spider.py", line 11, in <module>
    from collector.collector.items import CodingItem
  File "/var/www/site/RaPo3/collector/collector/items.py", line 21, in <module>
    from scrapy_djangoitem import DjangoItem
  File "/usr/local/lib/python2.7/dist-packages/scrapy_djangoitem/__init__.py", line 24, in <module>
    class DjangoItem(with_metaclass(DjangoItemMeta, Item)):
  File "/usr/lib/python2.7/dist-packages/six.py", line 617, in with_metaclass
    return meta("NewBase", bases, {})
  File "/usr/local/lib/python2.7/dist-packages/scrapy_djangoitem/__init__.py", line 13, in __new__
    if cls.django_model:
AttributeError: type object 'NewBase' has no attribute 'django_model'
```

**Comment by ShadowLL** [comment]
I found a same problem in my project. Have you fix this problem?

**Comment by ShadowLL** [comment]
Maybe you will find the answer from https://stackoverflow.com/questions/41529526/tensorflow-attributerror-type-object-newbase-has-no-attribute-is-abstract
